file = open("text.txt", "r")
slova = file.read()
print(slova)
file.close()
file = open("text.txt", "r")
stroki = file.readlines()
print(f"Кол-во строк: {len(stroki)}")
file.close()
file = open("text.txt", "r")
strbook = file.readlines()
for i in range(len(strbook)):
    print(f"В строке {i+1} символов {len(strbook[i])}")
file.close()
file = open("text.txt", "r")
v = file.read()
fa = v.split()
print(f"Кол-во слов: {len(fa)}")
